@startuml AcceptRejectCoachingRequest
actor Coach as user
participant "Front-end" as client
participant "Back-end" as server 
database "Database" as db

autonumber 1.1 "<b>0:"



user -> client++ : Click Accecpt / Reject account button

client -> server++ : PUT: api/Coach/coaching-request/{requestId}
server -> db++ : Get coaching request by requestId
db --> server : Retrived data
deactivate db

alt No data
    server --> client : Request not found notification
    client -> client++ : Display error message
    deactivate client
    deactivate client 
    |||
else Has data
    alt Accecpt
        server -> db++ : Update request status to "Accecpt"
        deactivate db
        |||
    else Reject
        server -> db++ : Update request status to "Reject"
        deactivate server
        deactivate db
        |||
    end
    |||
end 
@enduml