@startuml AcceptRejectCoachVerifyRequest
skinparam sequenceMessageAlign center
skinparam sequenceGroupFontSize 20
skinparam sequenceGroupHeaderFontSize 20
skinparam sequence {
    ParticipantFontSize 20
    ActorFontSize 20
    DatabaseFontSize 20
    ArrowFontSize 18
} 
actor Admin as user
participant "Front-end" as client
participant "Back-end" as server 
database "Database" as db

user -> client++ : Click Accecpt/Reject button on verification request
client -> server++ : PUT: api/Admin/coach-account-status/{userId}
server -> db++ : Get certificate submission\nby id
db --> server : Retrived data
deactivate db

alt No data
    server --> client : Request not found
    client -> client++ : Display error message
    deactivate client
    |||
else Has data
    server -> db++: Update certificate submission\nUpdate coach verification status
    deactivate db
    server --> client : Update message
    deactivate
    client -> client++ : Display message
    deactivate
    deactivate
    |||
end 
@enduml