@startuml Chat
actor Sender as sender
actor Receiver as receiver
participant "Front-end" as client
participant "Back-end" as server
database "Database" as db

autonumber 1.1 "<b>0:"

sender -> client++ : Choose the receiver
sender -> client : Send chat message
client -> server++ : Pass senderId, chat message and receiverId
server -> db++ : Save chat message from sender to receiver
server -> db : Get chat message from sender to receiver
db --> server : Retrive chat message from sender to receiver
deactivate db
server --> client : Chat message from sender to receiver
client --> receiver : See chat from sender

@enduml