@startuml CreateAdmin
skinparam sequenceMessageAlign center
skinparam sequenceGroupFontSize 14
skinparam sequenceGroupHeaderFontSize 15
skinparam sequence {
    ParticipantFontSize 20
    ActorFontSize 20
    DatabaseFontSize 20
    ArrowFontSize 18
} 
actor SuperAdmin as user
participant "Front-end" as client
participant "Back-end" as server 
database "Database" as db


user -> client++ : Click create admin
client -> client++: Show form input
user -> client: Enter admin information
deactivate
client -> server++ : POST: api/SuperAdmin/admin
server -> db++ : Check existence username
db --> server : Retrived result
deactivate db

alt Existed
    server --> client : Existed message
    client -> client++ : Display error message 
    deactivate client
    |||
else Not existed
    server -> db++ : Save new admin
    deactivate
    deactivate
    deactivate
end 
@enduml