@startuml CreateCourse
skinparam sequenceMessageAlign center
skinparam sequenceGroupFontSize 20
skinparam sequenceGroupHeaderFontSize 20
skinparam sequence {
    ParticipantFontSize 20
    ActorFontSize 20
    DatabaseFontSize 20
    ArrowFontSize 18
} 
actor Coach as user
participant "Front-end" as client
participant "Back-end" as server 
database "Database" as db


user -> client++ :Enter information and click add training course button
client -> server++ : POST: api/Coach/training-course
server -> db++ : Save new course
deactivate db
 
alt Success
    server --> client : Create message
    client -> client++ : Display message
    deactivate client
    |||
else Fail
    server --> client : Error message
    deactivate server
    client -> client++ : Display error
    deactivate client
    deactivate client
    |||
end
@enduml