@startuml ForgotPassword

actor "Authenticated\nUser" as user
participant "Front-end" as client
participant "Back-end" as server 
database "Database" as db

autonumber 1.1 "<b>0:"

user -> client++ : Click Forgot password button
client -> server++ : Get: api/User/password-forgot
deactivate client
server -> db++ : Check user by inputed email
db --> server : Retrived result
deactivate db

alt Valid result
    server --> user : Send reset password confirm email
    autonumber inc A
    user -> client++ : Confirm and input new password
    client -> server : Post: api/User/password-reset
    server -> server++ : valid new password
    deactivate server

    alt Valid
        server -> db++ : update new password 
        db --> server : Update result
        deactivate db
        client -> client++ : Display success message
        deactivate client
        |||
    else Invalid
        server --> client : Error result message
        client -> client++ : Display error
        deactivate client
        |||
    end
    |||

else Invalid result
    server --> client : Invalid for reset password notification
    deactivate server
    client -> client++ : Display error message
    deactivate client
    deactivate client 
    |||
end 

@enduml