@startuml ForgotPassword
skinparam sequenceMessageAlign center
skinparam sequenceGroupFontSize 14
skinparam sequenceGroupHeaderFontSize 15
skinparam sequence {
    ParticipantFontSize 20
    ActorFontSize 20
    DatabaseFontSize 20
    SequenceMessageFontSize 30
} 
actor "Authenticated\nUser" as user
participant "Front-end" as client
participant "Back-end" as server 
database "Database" as db


user -> client++ : Click Forgot password button
client -> server++ : GET: api/User/password-forgot
deactivate client
server -> db++ : Check user by email
db --> server : Retrived result
deactivate db

alt Valid user
    server --> user : Send reset password email
    user -> client++ : Enter new password
    client -> server : POST: api/User/password-reset
    server -> server++ : validate new password
    deactivate server

    alt Valid password
        server -> db++ : update new password
        deactivate db
        server -> server++ : Display success message
        deactivate
        |||
    else Invalid password
        server -> server++ : Display error
        deactivate
        |||
    end
    |||

else Invalid result
    server --> client : Invalid message
    deactivate server
    client -> client++ : Display message
    deactivate client
    deactivate client 
end 

@enduml