@startuml Login

actor Guest as user
participant "Front-end" as client
participant "Back-end" as server 
database "Database" as db

autonumber 1.1 "<b>0:"

user -> client++ : Click login button
client -> server++ : POST: api/User/login
server -> db++ : Get user by username
db --> server : Retrived user
deactivate db
server -> server++: Verify user
deactivate server

alt Valid user
    server -> client : Tokens
    |||
else Unvalid user
    server --> client : Unvalid user notification
    deactivate
    client -> client++ : Display error message
    deactivate
    deactivate  
    |||
end 

@enduml