@startuml Payment
skinparam sequenceMessageAlign center
skinparam sequenceGroupFontSize 20
skinparam sequenceGroupHeaderFontSize 20
skinparam sequence {
    ParticipantFontSize 20
    ActorFontSize 20
    DatabaseFontSize 20
    ArrowFontSize 18
} 
actor "Client" as client
participant "VNPay Service" as vnpay
participant "Front-end" as fe
participant "Back-end" as be
database "Database" as db
client -> fe++: Click payment button
fe -> be++: GET /api/Client/coaching-request/requestId/payment-url
be -> db++: Find coaching request
db --> be: Find result
deactivate

alt request exists
    be --> fe: Payment url
    fe --> vnpay++: Redirect
    vnpay -> vnpay++: Display payment methods
    client -> vnpay: Choose payment method and pay money
    vnpay -> be: Send payment result
    deactivate
    deactivate
    be -> be++: Display payment result
    opt Pay successfully
        be -> db++: Update coaching request
        deactivate
        deactivate
        |||
    end
    |||
else request does not exist
    be --> fe: Not found
    deactivate
    fe -> fe++: Display not found message
    deactivate
    deactivate
    |||
end
@enduml