@startuml Profile

actor "Authenticated\nUser" as user
participant "Front-end" as client
participant "Back-end" as server 
database "Database" as db

autonumber "<b>0:"

user -> client : Click profile tab 
client -> server : Get: api/User/profile
server -> db : Retrive logged user infomation
db --> server : Retrived Data

alt Has data
    server --> client : Retrived the user information
    client -> client : Display data

else No data
    server --> client : User not found message
    client -> client : Display error message 
    |||
end 
@enduml