@startuml Register
' skinparam sequenceMessageAlign center
skinparam sequenceGroupFontSize 20
skinparam sequenceGroupHeaderFontSize 20
skinparam sequence {
    ParticipantFontSize 20
    ActorFontSize 20
    DatabaseFontSize 20
    ArrowFontSize 18
} 
actor Guest as user
participant "Front-end" as client
participant "Back-end" as server 
database "Database" as db

user -> client++ : Click register button
client -> client++: Show register modal
user -> client: Enter information
deactivate
client -> server++ : POST api/User/register
server -> db++ : Check existence username, email and phone
db --> server : Result
deactivate

alt Existed
    server --> client : Existed errors
    client -> client++ : Display error message 
    deactivate 
    |||
else Not existed
    server -> db++ : Save new user
    deactivate
    server --> client : Registered message
    client -> client++ : Display message
    deactivate
    server --> user : Send\nconfirmation email
    user -> server : Click verification url
    server -> server++: Verify user
    server -> db++ : Update user verification
    deactivate
    deactivate
    deactivate
    deactivate
end 
@enduml