@startuml Register
actor Guest as user
participant "Front-end" as client
participant "Back-end" as server 
database "Database" as db

autonumber "<b>0:"

user -> client : Click register button
client -> server : POST: api/User/register
server -> db : Check existence username, email and phone
db --> server : Retrived result

alt Existence
    server --> client : Infomation existed notification
    client -> client : Display error message 
    |||
else Non-existence
    server -> db : Save registered user
    db --> server : Save data result
    alt Success
        server --> client : Register success message
        client -> client : Display message
        server --> user : Send email-confirm email
        user -> server : Confirm email
        server -> db : Update email verify status
        |||
    else Fail
        server --> client : Error result message
        client -> client : Display error
        |||
    end
    |||
end 
@enduml