@startuml Register
actor Guest as user
participant "Front-end" as client
participant "Back-end" as server 
database "Database" as db

autonumber 1.1 "<b>0:"

user -> client++ : Click register button
client -> server++ : POST: api/User/register
server -> db++ : Check existence username, email and phone
db --> server : Retrived result
deactivate

alt Existence
    server --> client : Infomation existed notification
    client -> client++ : Display error message 
    deactivate 
    |||
else Non-existence
    server -> db++ : Save registered user
    db --> server : Save data result
    deactivate
    alt Success
        server --> client : Register success message
        client -> client++ : Display message
        deactivate
        server --> user : Send email-confirm email
        user -> server : Confirm email
        server -> db++ : Update email verify status
        deactivate
        |||
    else Fail
        server --> client : Error result message
        deactivate
        client -> client++ : Display error
        deactivate
        deactivate
        |||
    end
    |||
end 
@enduml