@startuml UpdateCourse
actor Coach as user
participant "Front-end" as client
participant "Back-end" as server 
database "Database" as db

autonumber "<b>0:"

user -> client : Click update course
client -> server : PUT: api/training-course/{courseId}
server -> db : Update course infomation
db --> server : Update data result

alt Success
    server --> client : Update success message
    client -> client : Display message
else Fail
    server --> client : Error result message
    client -> client : Display error
end
@enduml