@startuml ViewAllCoaches

actor Admin as user
participant "Front-end" as client
participant "Back-end" as server 
database "Database" as db

autonumber "<b>0:"

user -> client : "View all coaches" request
client -> server : Get: api/admin/coaches (for admins) \nGet: api/coaches (for other roles)
server -> db : Get list of coaches
db --> server : Retrived Data

alt Has data
    server -> server : Apply pagination
    server --> client : List of coaches
    client -> client : Display data
    |||

else No data
    server --> client : No coach found message
    client -> client : Display message 
    |||

else Error
    server --> client : Error message
    |||
end 

@enduml