@startuml ViewCoachVerifyRequest
skinparam sequenceMessageAlign center
skinparam sequence {
    ParticipantFontSize 20
    ActorFontSize 20
    DatabaseFontSize 20
    ArrowFontSize 18
} 
actor Admin as user
participant "Front-end" as client
participant "Back-end" as server 
database "Database" as db

user -> client++ : Click "verification requests" tab 
client -> server++ : Get: api/Admin/cert-requests
server -> db++ : Retrive all certifcate submission by status
db --> server : Retrived data
deactivate
server --> client : List of request
client -> client++ : Display list
deactivate

@enduml