@startuml ViewReportDetail
skinparam sequenceMessageAlign center
skinparam sequenceGroupFontSize 20
skinparam sequenceGroupHeaderFontSize 20
skinparam sequence {
    ParticipantFontSize 20
    ActorFontSize 20
    DatabaseFontSize 20
    ArrowFontSize 18
} 
actor Admin as user
participant "Front-end" as client
participant "Back-end" as server 
database "Database" as db

user -> client++ : View report detail
client -> server++ : Get: api/Admin/reports/{requestId}
server -> db++ : Retrive the report by id
db --> server : Retrived Data
deactivate

alt Has data
    server --> client : Retrived data
    client -> client++ : Display data
    deactivate

else No data
    server --> client : Not found
    deactivate
    client -> client++ : Display error message 
    deactivate
    deactivate
    |||
end 
@enduml