@startuml ViewTrainingCourseOfCoach

actor Guest as user
participant "Front-end" as client
participant "Back-end" as server 
database "Database" as db

autonumber 1.1 "<b>0:"

user -> client++ : "View coach training course" request 
client -> server++ : Get: api/coach/{coachId}/training-courses
server -> db++ : Retrive courses by coachId
db --> server : Retrived Data
deactivate

alt Has data
    server -> server++ : Apply pagination
    deactivate
    server --> client : Retrived courses
    client -> client++ : Display data
    deactivate

else No data
    server --> client : Coach not found message
    deactivate
    client -> client++ : Display error message 
    deactivate
    deactivate
    |||
end 
@enduml