@startuml ViewTraniningCourseDetail

actor Guest as user
participant "Front-end" as client
participant "Back-end" as server 
database "Database" as db

autonumber "<b>0:"

user -> client : Click on the course 
client -> server : Get: api/coach/{coachId}/training-course-detail/{courseId}
server -> db : Retrive training course by coachId and courseId
db --> server : Retrived Data

alt Has data
    server --> client : Retrived the course detail

    alt Client role
        server -> server : Check the course is requested\nby logged Client or not

        alt Requested
            server -> client : Unable to request course
            |||
        else Not yet
            server -> client : Able to request course
            |||
        end
    end

    client -> client : Display data

else No data
    server --> client : Course not found message
    client -> client : Display error message 
    |||
end 
@enduml