@startuml ViewCoachingRequests

actor Coach as user
participant "Front-end" as client
participant "Back-end" as server 
database "Database" as db

autonumber "<b>0:"

user -> client : Click coaching requests tab
client -> server : Get: api/Coach/coaching-requests
server -> db : Get coaching request to logged coach by status
db --> server : Retrived Data

alt Has data
    server -> server : Apply pagination
    server --> client : List of request
    client -> client : Display each request client information
    |||

else No data
    server --> client : No data found message
    client -> client : Display message 
    |||

else Error
    server --> client : Error message
    |||
end 

@enduml