@startuml ViewContractDetail
skinparam sequenceMessageAlign center
skinparam sequenceGroupFontSize 20
skinparam sequenceGroupHeaderFontSize 20
skinparam sequence {
    ParticipantFontSize 20
    ActorFontSize 20
    DatabaseFontSize 20
    ArrowFontSize 18
} 
actor "Coach/Client" as user
participant "Front-end" as client
participant "Back-end" as server 
database "Database" as db

user -> client++ : View report detail
client -> server++ : GET: api/Contract/{contractId}/detail 
server -> db++ : Retrive the contract by contract id
db --> server : Retrived Data
deactivate

alt Has data
    server --> client : Retrived data
    client -> client++ : Display data
    deactivate

else No data
    server --> client : Mot found message
    deactivate
    client -> client++ : Display not found message 
    deactivate
    deactivate
    |||
end 
@enduml