@startuml ViewAllReports

actor Guest as user
participant "Front-end" as client
participant "Back-end" as server 
database "Database" as db

autonumber 1.1 "<b>0:"

user -> client++ : View all reports 
client -> server++ : Get: api/Admin/reports
server -> db++ : Retrive all report by status
db --> server : Retrived Data
deactivate

alt Has data
    server -> server++ : Apply pagination
    deactivate
    server --> client : Retrived data
    client -> client++ : Display data
    deactivate

else No data
    server --> client : Data not found message
    deactivate
    client -> client++ : Display error message
    deactivate
    deactivate 
    |||
end 
@enduml