@startuml ViewCoachingRequests
skinparam sequenceMessageAlign center
skinparam sequenceGroupFontSize 20
skinparam sequenceGroupHeaderFontSize 20
skinparam sequence {
    ParticipantFontSize 20
    ActorFontSize 20
    DatabaseFontSize 20
    ArrowFontSize 18
} 
actor Coach as user
participant "Front-end" as client
participant "Back-end" as server 
database "Database" as db

user -> client++ : Click coaching requests tab
client -> server++ : GET: api/Coach/coaching-requests
server -> db++ : Get coaching requests
db --> server : Coaching requests
deactivate
server --> client : List of requests
deactivate
client -> client++ : Display requests
deactivate
deactivate

@enduml