@startuml ViewCoachVerifyRequestDetail

actor Admin as user
participant "Front-end" as client
participant "Back-end" as server 
database "Database" as db

autonumber 1.1 "<b>0:"

user -> client++ : "View coach training course" request 
client -> server++ : Get: api/Admin/cert-requests/{requestId}
server -> db++ : Retrive the request by id
db --> server : Retrived Data
deactivate

alt Has data
    server --> client : Retrived data
    client -> client++ : Display data
    deactivate

else No data
    server --> client : Data not found message
    deactivate
    client -> client++ : Display error message 
    deactivate
    |||
end 
@enduml