@startuml ViewTraniningCourseDetail
skinparam sequenceMessageAlign center
skinparam sequenceGroupFontSize 20
skinparam sequenceGroupHeaderFontSize 20
skinparam sequence {
    ParticipantFontSize 20
    ActorFontSize 20
    DatabaseFontSize 20
    ArrowFontSize 18
} 
actor "Guest/Client" as user
participant "Front-end" as client
participant "Back-end" as server 
database "Database" as db


user -> client++ : Click on the course 
client -> server++ : GET: api/Coach/{coachId}/training-course-detail/{courseId}
server -> db++ : Retrive training course by coachId and courseId
db --> server : Retrived Data
deactivate

alt Has data
    server --> client : Retrived the course detail

    client -> client++ : Display data
    deactivate

else No data
    server --> client : Course not found
    deactivate
    client -> client++ : Display not found message 
    deactivate
    deactivate
    |||
end 
@enduml