@startuml ViewCoachVerifyRequest

actor User as user
participant "ICoaching client" as client
participant "ICoaching server" as server 
database "MySQL" as db

autonumber "<b>0:"

user -> client : View certification verify requests 
client -> server : Get: api/Admin/cert-requests
server -> db : Retrive all certification request by status
db --> server : Retrived Data

alt Has data
    server -> server : Apply pagination
    server --> client : Retrived data
    client -> client : Display data

else No data
    server --> client : Data not found message
    client -> client : Display error message 
    |||
end 
@enduml