@startuml ViewClientContracts

actor Coach as user
participant "Front-end" as client
participant "Back-end" as server 
database "Database" as db

autonumber "<b>0:"

user -> client : Click Contract tabs
client -> server : Get: ---get client contract api---
server -> db : Get list of contract of logged client
db --> server : Retrived Data

alt Has data
    server -> server : Apply pagination
    server --> client : List of contracts
    client -> client : Display contracts
    |||

else No data
    server --> client : No data found message
    client -> client : Display message 
    |||
else Error
    server --> client : Error message
    |||
end 

@enduml