@startuml ViewCoachAboutme
skinparam sequenceMessageAlign center
skinparam sequenceGroupFontSize 20
skinparam sequenceGroupHeaderFontSize 20
skinparam sequence {
    ParticipantFontSize 20
    ActorFontSize 20
    DatabaseFontSize 20
    ArrowFontSize 18
} 
actor "Guest/Client" as user
participant "Front-end" as client
participant "Back-end" as server 
database "Database" as db


user -> client++ : Click "About me" tab on coach profile 
client -> server++ : GET: api/Coach/{coachId}/about-me
server -> db++ : Get by coachId
db --> server : Retrived Data
deactivate

alt Has data
    server --> client : Coach's about-me 
    client -> client++ : Display data
    deactivate

else No data
    server --> client : Coach not found message
    deactivate
    client -> client++ : Display error message
    deactivate
    deactivate 
    |||
end 
@enduml
