@startuml ViewAllCoaches
skinparam sequenceMessageAlign center
skinparam sequence {
    ParticipantFontSize 20
    ActorFontSize 20
    DatabaseFontSize 20
    ArrowFontSize 18
} 
actor User as user
participant "Front-end" as client
participant "Back-end" as server 
database "Database" as db


user -> client++ : "View all coaches" request
client -> server++ : GET: api/Admin/coaches (for admins)\nGET: api/Guest/coaches (client, guest)
server -> db++ : Get coaches
db --> server : coaches
deactivate

server --> client : List of coaches
client -> client++ : Display list
deactivate

@enduml